/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Application: typeof import('./../components/Application/Application.vue')['default']
    Bottom: typeof import('./../components/Layout/Bottom.vue')['default']
    DyAppLoading: typeof import('./../components/global/DyAppLoading.vue')['default']
    DyButton: typeof import('./../components/global/DyButton.vue')['default']
    DyCopy: typeof import('./../components/global/DyCopy.vue')['default']
    DyCutDown: typeof import('./../components/global/DyCutDown.vue')['default']
    DyFloatButton: typeof import('./../components/global/DyFloatButton.vue')['default']
    DyForm: typeof import('./../components/global/DyForm.vue')['default']
    DyInput: typeof import('./../components/global/DyInput.vue')['default']
    DyLogo: typeof import('./../components/global/DyLogo.vue')['default']
    DyNotic: typeof import('./../components/global/DyNotic.vue')['default']
    DyNumberAnimation: typeof import('./../components/global/DyNumberAnimation.vue')['default']
    DyPage: typeof import('./../components/global/DyPage.vue')['default']
    DyPopup: typeof import('./../components/global/DyPopup.vue')['default']
    DyRotateArrow: typeof import('./../components/global/DyRotateArrow.vue')['default']
    DySkeleton: typeof import('./../components/global/DySkeleton.vue')['default']
    Header: typeof import('./../components/Header/Header.vue')['default']
    Home: typeof import('./../views/Home/Home.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NavBack: typeof import('./../components/Nav/NavBack.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NFlex: typeof import('naive-ui')['NFlex']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NSelect: typeof import('naive-ui')['NSelect']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NStep: typeof import('naive-ui')['NStep']
    NSteps: typeof import('naive-ui')['NSteps']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    Page: typeof import('./../components/Layout/Page.vue')['default']
    PageSider: typeof import('./../components/Layout/PageSider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Web3Manager: typeof import('./../components/Web3Manager/Web3Manager.vue')['default']
    Web3Status: typeof import('./../components/Header/Web3Status.vue')['default']
  }
}
